# Generated by Django 4.2.5 on 2023-09-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('initial', models.CharField(blank=True, max_length=32, null=True)),
                ('employee_age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'M'), ('f', 'F'), ('t', 'T')], max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('marital_status', models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=32, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=32, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('login_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.loginuser')),
            ],
            options={
                'db_table': 'employee_detail',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_no', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_no_sequence', models.IntegerField(blank=True, null=True)),
                ('ticket_description', models.TextField(blank=True, null=True)),
                ('ticket_status', models.IntegerField(blank=True, choices=[(1, 'ToDo'), (2, 'Inprogress'), (3, 'Completed'), (4, 'Hold')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=32, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_admin', to='employee.employee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
